manager_app_homepage:
    path:     /manager
    defaults: { _controller: ManagerAppBundle:App:index }

app_calendar:
    path:     /manager/calendar
    defaults: { _controller: ManagerAppBundle:App:index }

app_contacts:
    path:     /manager/calendar
    defaults: { _controller: ManagerAppBundle:App:index }