manager_app_homepage:
    path:     /
    defaults: { _controller: ManagerAppBundle:App:index }

manager_member:
    resource: "@ManagerMemberBundle/Resources/config/routing.yml"
    prefix:   /member

manager_secretaria:
    resource: "@ManagerSecretariaBundle/Resources/config/routing.yml"
    prefix:   /secretaria




app_calendar:
    path:     /calendar
    defaults: { _controller: ManagerAppBundle:App:index }

app_contacts:
    path:     /contact
    defaults: { _controller: ManagerAppBundle:App:index }

app_profile:
    path:     /
    defaults: { _controller: ManagerMemberBundle:Default:index }