security_user:
    resource: "@SecurityUserBundle/Resources/config/routing.yml"
    prefix:   /user

manager_app:
    resource: "@ManagerAppBundle/Resources/config/routing.yml"
    prefix:   /manager

learning_app:
    resource: "@LearningAppBundle/Resources/config/routing.yml"
    prefix:   /learning
