security_user:
    resource: "@SecurityUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

manager_app:
    resource: "@ManagerAppBundle/Resources/config/routing.yml"
    prefix:   /manager

learning_app:
    resource: "@LearningAppBundle/Resources/config/routing.yml"
    prefix:   /learning