manager_user_homepage:
    path:     /
    defaults: { _controller: ManagerUserBundle:Default:index }

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: ManagerUserBundle:Default:index }

app_profile:
    path:     /profile
    defaults: { _controller: ManagerUserBundle:Default:index }